name: Deploy to Production

on:
  release:
    types:
      - published

jobs:
  deploy:

    runs-on:
      - self-hosted
      - production
    env:
      ENVIRONMENT: production
      DOMAIN: ${{ secrets.DOMAIN_PRODUCTION }}
      STACK_NAME: ${{ secrets.STACK_NAME_PRODUCTION }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      FRONTEND_HOST: ${{ secrets.FRONTEND_HOST }}
      BACKEND_CORS_ORIGINS: ${{ secrets.BACKEND_CORS_ORIGINS }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAILS_FROM_EMAIL: ${{ secrets.EMAILS_FROM_EMAIL }}
      POSTGRES_SERVER: db
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      DOCKER_IMAGE_BACKEND: ${{ secrets.DOCKER_IMAGE_BACKEND }}
      DOCKER_IMAGE_FRONTEND: ${{ secrets.DOCKER_IMAGE_FRONTEND }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          cat > .env << EOF
          ENVIRONMENT=${{ env.ENVIRONMENT }}
          DOMAIN=${{ env.DOMAIN }}
          STACK_NAME=${{ env.STACK_NAME }}
          SECRET_KEY=${{ env.SECRET_KEY }}
          FIRST_SUPERUSER=${{ env.FIRST_SUPERUSER }}
          FIRST_SUPERUSER_PASSWORD=${{ env.FIRST_SUPERUSER_PASSWORD }}
          FRONTEND_HOST=${{ env.FRONTEND_HOST }}
          BACKEND_CORS_ORIGINS=${{ env.BACKEND_CORS_ORIGINS }}
          SMTP_HOST=${{ env.SMTP_HOST }}
          SMTP_USER=${{ env.SMTP_USER }}
          SMTP_PASSWORD=${{ env.SMTP_PASSWORD }}
          EMAILS_FROM_EMAIL=${{ env.EMAILS_FROM_EMAIL }}
          POSTGRES_SERVER=${{ env.POSTGRES_SERVER }}
          POSTGRES_PORT=${{ env.POSTGRES_PORT }}
          POSTGRES_DB=${{ env.POSTGRES_DB }}
          POSTGRES_USER=${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }}
          SENTRY_DSN=${{ env.SENTRY_DSN }}
          DOCKER_IMAGE_BACKEND=${{ env.DOCKER_IMAGE_BACKEND }}
          DOCKER_IMAGE_FRONTEND=${{ env.DOCKER_IMAGE_FRONTEND }}
          EOF
      - run: docker compose -f docker-compose.yml --project-name ${{ secrets.STACK_NAME_PRODUCTION }} build
      - run: docker compose -f docker-compose.yml --project-name ${{ secrets.STACK_NAME_PRODUCTION }} up -d
